name: Deploy Backend

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to VPS as root and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_IP }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/back-end

            # Lấy code mới nhất
            git fetch
            git checkout production
            git pull origin production

            # Tạo Firebase key từ secret
            mkdir -p /var/www/back-end/BE/GRRWS.Host/Keys
            echo '${{ secrets.FIREBASE_KEY }}' > /var/www/back-end/BE/GRRWS.Host/Keys/koiveterinaryservicecent-925db-firebase-adminsdk-vus2r-2b14e43049.json
            chmod 600 /var/www/back-end/BE/GRRWS.Host/Keys/koiveterinaryservicecent-925db-firebase-adminsdk-vus2r-2b14e43049.json

            # Tạo GG Cloud Vision key từ secret
            echo '${{ secrets.GG_CLOUD_VISION }}' > /var/www/back-end/BE/GRRWS.Host/Keys/sewing-465209-a154d5504a11.json
            chmod 600 /var/www/back-end/BE/GRRWS.Host/Keys/sewing-465209-a154d5504a11.json

            # Copy vào thư mục publish
            mkdir -p /var/www/back-end/publish/Keys
            cp /var/www/back-end/BE/GRRWS.Host/Keys/koiveterinaryservicecent-925db-firebase-adminsdk-vus2r-2b14e43049.json /var/www/back-end/publish/Keys/
            cp /var/www/back-end/BE/GRRWS.Host/Keys/sewing-465209-a154d5504a11.json /var/www/back-end/publish/Keys/

            # Deploy app
            bash ./deploy.sh
